version: '3'
# postgres Database
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432  # make sure you don't have another container running on 5432

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

# Adminer is Interface for Database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# postgresql://admin:admin@localhost:5432/postgres